### ISSUE TITLE
grizzly-cli: build trigger by run is missing required arguments in namespace

### ISSUE THREAD

**Issue by mgor** [Biometria-se/grizzly#347]
**Describe the bug**
```
Successfully installed setuptools-75.1.0 setuptools_scm-8.1.0
Traceback (most recent call last):
  File "/workspaces/grizzly/tests/project/.venv/bin/grizzly-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/__main__.py", line 176, in main
    rc = distributed(args)
         ^^^^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/distributed/__init__.py", line 146, in distributed
    return run(args, distributed_run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/utils.py", line 559, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/run.py", line 443, in run
    return run_func(args, environ, run_arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/distributed/__init__.py", line 273, in distributed_run
    rc = do_build(args)
         ^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/utils.py", line 559, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/grizzly/tests/project/.venv/lib/python3.12/site-packages/grizzly_cli/distributed/build.py", line 148, in build
    spinner = 'building' if not args.no_progress else None
                                ^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'no_progress'`
```

**Comment by mgor** [comment]
fixed in Biometria-se/grizzly-cli#99.
